import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import { FormEvent } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [urlLink, setUrlLink] = useState("");
  const [shortLink, setShortLink] = useState("");

  const onSubmit = async (e: FormEvent) => {
    e.preventDefault();
    const data = {
      url: urlLink,
    };
    const response = await fetch("/api/shortner", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(data),
    });
    const resData = await response.json();
    setShortLink(resData.message);
  };

  const copyLink = (e: any) => {
    navigator.clipboard.writeText(shortLink);
    alert("Link Copied!")
  };

  const renderInfo = () => {
    if (shortLink.length == 0) {
      return (
        <>
          <b>The link will be valid for 3 Minutes only!</b>
        </>
      );
    }
    return (
      <>
        <button className={styles.copy} onClick={copyLink}>
          Copy The Link!
        </button>
      </>
    );
  };

  return (
    <>
      <Head>
        <title>URL Shortner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>URL Shortner</h1>
          <form onSubmit={onSubmit}>
            <input
              name="url"
              className={styles.inp}
              onChange={(e) => setUrlLink(e.target.value)}
              type="text"
            />
            <br />
            <button
              type="submit"
              disabled={urlLink.length == 0}
              className={
                urlLink.length == 0 ? styles.submit_dis : styles.submit
              }
            >
              Submit
            </button>
          </form>
          <div className={styles.info}>{renderInfo()}</div>
        </div>
      </main>
    </>
  );
}
